### ISSUE TITLE
EncodedVideoFrame needs to be marked serializable

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-encoded-transform#181]
The algorithm specified seems to indicate that EncodedVideoFrame (and audio) is serializable, since it uses the serialization steps to move it around.

This means that "structuredClone(frame)" should give sensible results.

We should mark the IDL accordingly.

(Related to #161)

**Comment by youennf** [comment]
The spec is using serialise with transfer as a way to copy the detach the data ownership and ensure there is no TOCTOU issue. I do not think the intent was to enable serialisation of frames.
We can rewrite the spec to detach the array buffer and copy the necessary information to make things clearer.
We can discuss making frames serialisable in parallel.

**Comment by jan-ivar** [comment]
> The spec is using serialise with transfer as a way to copy the detach the data ownership and ensure there is no TOCTOU issue. I do not think the intent was to enable serialisation of frames.
We can rewrite the spec to detach the array buffer and copy the necessary information to make things clearer.

Thanks for explaining. I agree that unless the WG decides frames should be serializable, we need to rewrite that since neither RTCEncodedAudioFrame nor RTCEncodeVideoFrame contain the prerequisite [serialization](https://html.spec.whatwg.org/multipage/structured-data.html#serialization-steps) or [deserialization](https://html.spec.whatwg.org/multipage/structured-data.html#deserialization-steps) steps necessary to [have](https://w3c.github.io/webrtc-encoded-transform/#abstract-opdef-writeencodeddata) _"Let serializedFrame be [StructuredSerializeWithTransfer](https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializewithtransfer)(frame, « data »)."_ and _"Let frameCopy be [StructuredDeserialize](https://html.spec.whatwg.org/multipage/structured-data.html#structureddeserialize)(serializedFrame, frame’s [relevant realm](https://html.spec.whatwg.org/multipage/webappapis.html#concept-relevant-realm))."_ work.

> We can discuss making frames serialisable in parallel.

To save time, can this be that issues?
- If we decide NO, we do a PR with the above rewrite
- If we decide YES, we do a PR with the missing (de)serialization steps, and [Serializable] in the WebIDL

Does that work?

**Comment by jan-ivar** [comment]
@alvestrand's request seems based on need in the https://github.com/w3c/webrtc-encoded-transform/issues/160 use case, and  now that [structuredClone(value[, { transfer }])](https://html.spec.whatwg.org/multipage/structured-data.html#structured-cloning) exists in the web platform, inventing custom `frame.clone()` methods like in https://github.com/w3c/webrtc-encoded-transform/issues/161 seems wrong to me.

This would also solve whether to clone the frame buffer or not, by leaving it up to JS:
```js
const frameCopy = structuredSerialize(frame); // clones the data as well

const frameMove = structuredSerialize(frame, {transfer: [frame.data]}); // transfers the data
```
